
server:
  port: 9001
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    active: test
  application:
    name:  demo-basic
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
feign:
  hystrix:
    enabled: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
mybatis:
    mapper-locations: classpath:mapper/*.xml



dubbo:
 registry:
  check: false
  address: nacos://192.168.2.7:8848
 application:
  name: basic-dubbo
 scan:
  basePackages: com.demo.basic.service.impl.dubbo
 protocol:
  name: dubbo
  port: -1
 consumer:
  check: false
jwt:
  # 密匙KEY
  secret: QzQ1MjhFMzdBNzhDOTI3QTkzOEE2QzJBN0Q1MUY5N0Y
  # HeaderKEY
  tokenHeader: Authorization
  # Token前缀字符
  tokenPrefix: sunYF-
  # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
  expiration: 86400
  # 配置不需要认证的接口
  #antMatchers: /index/**,/login/**,/favicon.ico
seata:
  enabled: true
  application-id: demo-basic
  tx-service-group: demo-basic-group
  enableAutoDataSourceProxy: true
  excludes-for-auto-proxying: firstClassNameForExclude,secondClassNameForExclude
  #
  client:
    rm:
      async-commit-buffer-limit: 1000
      report-retry-count: 5
      table-meta-check-enable: false
      report-success-enable: false
      saga-branch-register-enable: false
      lock:
        retry-interval: 10
        retry-times: 30
        retry-policy-branch-rollback-on-conflict: true
    tm:
      degrade-check: false
      degrade-check-period: 2000
      degrade-check-allow-times: 10
      commit-retry-count: 5
      rollback-retry-count: 5
    undo:
      data-validation: true
      log-serialization: jackson
      log-table: undo_log
      only-care-update-columns: true
    log:
      exceptionRate: 100
  service:
    vgroup-mapping:
      demo-basic-group: default
    grouplist:
      default: 127.0.0.1:8091
    enable-degrade: false
    disableGlobalTransaction: false
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
      #      worker-thread-size: default
      boss-thread-size: 1
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    enable-client-batch-send-request: true
  config:
    type: nacos
    nacos:
      #      namespace:
      serverAddr: 127.0.0.1:8848
      group: DEFAULT_GROUP
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group : DEFAULT_GROUP
      #      namespace:
      username: nacos
      password: nacos


---
spring:
  profiles: test
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

---
spring:
  profiles: dev
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
