package com.demo.order.entity;

import com.demo.order.enums.moldtype.SexEnum;
import java.time.LocalDateTime;
import javax.persistence.*;

import com.demo.order.enums.handler.SexEnumHandler;
import lombok.Data;
import lombok.experimental.Accessors;
import tk.mybatis.mapper.annotation.ColumnType;

@Data
@Accessors(chain = true)
@Table(name = "`admin_user_t`")
public class AdminUserT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.id
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.login_name
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.password
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.nick_name
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.real_name
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.sex
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    @ColumnType(typeHandler = SexEnumHandler.class)
    private SexEnum sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.phone
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.email
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.remark
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.locked
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private Boolean locked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.create_id
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private String createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.create_time
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.update_id
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.update_time
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.version
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.removed
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private Boolean removed;
}