package com.demo.order.entity;

import java.time.LocalDateTime;
import javax.persistence.*;
import lombok.Data;
import lombok.experimental.Accessors;

@Data
@Accessors(chain = true)
@Table(name = "`admin_role_permission_t`")
public class AdminRolePermissionT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role_permission_t.id
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role_permission_t.admin_role_t_id
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private String adminRoleTId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role_permission_t.admin_permission_t_id
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private String adminPermissionTId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role_permission_t.create_id
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private String createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role_permission_t.create_time
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role_permission_t.update_id
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role_permission_t.update_time
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role_permission_t.version
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_role_permission_t.removed
     *
     * @mbg.generated Sun Feb 28 13:37:16 CST 2021
     */
    private Boolean removed;
}