package com.demo.basic.entity;

import java.time.LocalDateTime;
import javax.persistence.*;
import lombok.Data;
import lombok.experimental.Accessors;

@Data
@Accessors(chain = true)
@Table(name = "`admin_user_t`")
public class AdminUserT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.id
     *
     * @mbg.generated Mon Nov 30 14:31:50 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.login_name
     *
     * @mbg.generated Mon Nov 30 14:31:50 CST 2020
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.password
     *
     * @mbg.generated Mon Nov 30 14:31:50 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.nick_name
     *
     * @mbg.generated Mon Nov 30 14:31:50 CST 2020
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.real_name
     *
     * @mbg.generated Mon Nov 30 14:31:50 CST 2020
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.phone
     *
     * @mbg.generated Mon Nov 30 14:31:50 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.email
     *
     * @mbg.generated Mon Nov 30 14:31:50 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.remark
     *
     * @mbg.generated Mon Nov 30 14:31:50 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.locked
     *
     * @mbg.generated Mon Nov 30 14:31:50 CST 2020
     */
    private Boolean locked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.create_id
     *
     * @mbg.generated Mon Nov 30 14:31:50 CST 2020
     */
    private String createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.create_time
     *
     * @mbg.generated Mon Nov 30 14:31:50 CST 2020
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.update_id
     *
     * @mbg.generated Mon Nov 30 14:31:50 CST 2020
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.update_time
     *
     * @mbg.generated Mon Nov 30 14:31:50 CST 2020
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.version
     *
     * @mbg.generated Mon Nov 30 14:31:50 CST 2020
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_t.removed
     *
     * @mbg.generated Mon Nov 30 14:31:50 CST 2020
     */
    private Boolean removed;
}