version: "3"
services: 
  industrial-vue: #vue前端服务 
    container_name: industrial-vue
    image: nginx
    ports: 
      - "8502:80"
    volumes: 
      #挂载dist静态资源到容器中
      - /home/industrial/industrial-vue/dist/:/usr/share/nginx/html/
      #挂载nginx配置文件到容器中，替换nginx容器中的默认配置
      - /home/industrial/industrial-vue/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    build: 
     context: ./
     dockerfile: Dockerfile
